apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  shareProcessNamespace: true
  containers:
  - name: hello-world
    image: java-hello-world
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /dumps
      name: dumps

  - name: uploader-sidecar
    image: uploader-sidecar
    imagePullPolicy: Never
    args: ["/dumps", "TEST-BUCKET", "dumps-prefix/", "--dry"]
    volumeMounts:
    - mountPath: /dumps
      name: dumps     

  - name: thread-dumper
    image: java-hello-world
    command: ["./thread-dumper.sh"]
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /dumps
      name: dumps

  volumes:
  - name: dumps
    emptyDir: {}
